[window]
dimensions = { columns = 80, lines = 25 }
resize_increments = true

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 15

[mouse]
hide_when_typing = true

[general]
import = [
  "~/.config/alacritty/kanagawabones.toml"
]
