# Colors (kanagawabones)
# Modified to shift cyan hue by -20 degrees

[colors.cursor]
cursor = '#e6e0c2'
text = '#1f1f28'

[colors.selection]
background = '#49473e'
text = '#ddd8bb'

[colors.primary]
background = '#1f1f28'
foreground = '#ddd8bb'

[colors.normal]
black = '#1f1f28'
blue = '#7eb3c9'
# cyan = '#7eb3c9'
cyan = '#957fb8'
green = '#98bc6d'
magenta = '#957fb8'
red = '#e46a78'
white = '#ddd8bb'
yellow = '#e5c283'

[colors.bright]
black = '#3c3c51'
blue = '#7bc2df'
# cyan = '#7bc2df'
cyan = '#a98fd2'
green = '#9ec967'
magenta = '#a98fd2'
red = '#ec818c'
white = '#a8a48d'
yellow = '#f1c982'
